# Generated by Django 5.2.17 on 2026-09-16 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workbook_filename', models.CharField(max_length=255)),
                ('workbook_sha256', models.CharField(db_index=True, max_length=64)),
                ('sheet_name', models.CharField(max_length=100)),
                ('parser_version', models.CharField(max_length=50)),
                ('dry_run', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RUNNING', 'Sedang berjalan'), ('COMPLETED', 'Selesai'), ('FAILED', 'Gagal')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('raw_rows_seen', models.PositiveIntegerField(default=0)),
                ('raw_rows_created', models.PositiveIntegerField(default=0)),
                ('raw_rows_already_existing', models.PositiveIntegerField(default=0)),
                ('blank_rows_seen', models.PositiveIntegerField(default=0)),
                ('staging_rows_created', models.PositiveIntegerField(default=0)),
                ('staging_rows_already_existing', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workbook_sha256', models.CharField(db_index=True, max_length=64)),
                ('sheet_name', models.CharField(max_length=100)),
                ('source_row_number', models.PositiveIntegerField()),
                ('is_blank', models.BooleanField(default=False)),
                ('raw_json', models.JSONField(help_text='Enam nilai asli + tipe sel, apa adanya dari workbook.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_seen_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_rows_first_seen', to='imports.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='StagingRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parser_version', models.CharField(max_length=50)),
                ('legacy_nomor_raw', models.CharField(blank=True, max_length=255)),
                ('serial_number_raw', models.CharField(blank=True, max_length=255)),
                ('serial_number_present', models.BooleanField(default=False)),
                ('customer_name_raw', models.CharField(blank=True, max_length=255)),
                ('customer_name_normalized', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sent_at_raw', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateField(blank=True, null=True)),
                ('sent_at_is_native', models.BooleanField(default=False)),
                ('sent_at_parseable', models.BooleanField(default=False)),
                ('returned_at_raw', models.CharField(blank=True, max_length=255)),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('returned_at_is_native', models.BooleanField(default=False)),
                ('returned_status', models.CharField(choices=[('NONE', 'Kosong'), ('DATE', 'Tanggal'), ('K', 'K'), ('KEMBALI', 'KEMBALI'), ('SDH_KEMBALI', 'SDH KEMBALI'), ('SDH_BALIK', 'SDH BALIK (belum dipetakan - MIG-B05)'), ('OTHER_TEXT', 'Teks lain tidak dikenal')], default='NONE', max_length=20)),
                ('returned_date_unknown', models.BooleanField(default=False, help_text='True bila status kembali dikenal (K/KEMBALI/SDH KEMBALI) tapi tanpa tanggal terparse - occurred_at tidak pernah diisi tanggal impor (MIG-B04).')),
                ('gas_code_raw', models.CharField(blank=True, max_length=255)),
                ('gas_type_code', models.CharField(blank=True, max_length=10)),
                ('gas_type_known', models.BooleanField(default=False)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, help_text='Kunci kandidat duplikat bisnis (mengabaikan kolom Nomor) - lihat B3.', max_length=512)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('READY', 'Siap direview'), ('NEEDS_REVIEW', 'Perlu review'), ('ERROR', 'Error - tidak bisa membentuk lifecycle')], default='READY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staging_rows_created_in', to='imports.importbatch')),
                ('raw_row', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staging_row', to='imports.rawrow')),
            ],
        ),
        migrations.AddIndex(
            model_name='rawrow',
            index=models.Index(fields=['workbook_sha256', 'is_blank'], name='imports_raw_workboo_b06d16_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawrow',
            constraint=models.UniqueConstraint(fields=('workbook_sha256', 'sheet_name', 'source_row_number'), name='uniq_raw_row_per_snapshot_position'),
        ),
        migrations.AddIndex(
            model_name='stagingrow',
            index=models.Index(fields=['review_status'], name='imports_sta_review__3f465a_idx'),
        ),
    ]
