# Generated by Django 5.2.17 on 2026-09-16 02:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('operations', '0003_alter_cycle_data_quality_flag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RUNNING', 'Sedang berjalan'), ('COMPLETED', 'Selesai'), ('FAILED', 'Berhenti karena error (bisa di-resume)')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('groups_seen', models.PositiveIntegerField(default=0)),
                ('groups_already_resolved', models.PositiveIntegerField(default=0)),
                ('groups_published', models.PositiveIntegerField(default=0)),
                ('groups_blocked', models.PositiveIntegerField(default=0)),
                ('rows_published', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('EXCLUDE', 'Kecualikan dari publish')], max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='stagingrow',
            name='publish_outcome',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Menunggu review/publish'), ('PUBLISHED', 'Sudah dipublish'), ('EXCLUDED_APPROVED', 'Dikecualikan Admin (beralasan)')], db_index=True, default='PENDING_REVIEW', help_text='F4: hasil review/publish. Rekonsiliasi wajib raw(non-blank) = PUBLISHED + PENDING_REVIEW + EXCLUDED_APPROVED - lihat docs/reports/F4.md.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stagingrow',
            index=models.Index(fields=['serial_number_raw'], name='imports_sta_serial__52c825_idx'),
        ),
        migrations.AddField(
            model_name='publishbatch',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='staging_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='imports.stagingrow'),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='operations.cycle'),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='publish_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='imports.publishbatch'),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='raw_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='imports.rawrow'),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='staging_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='source_link', to='imports.stagingrow'),
        ),
    ]
