# Generated by Django 5.2.17 on 2026-09-16 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT', 'Out'), ('LOST', 'Lost'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], db_index=True, default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='GasType',
            fields=[
                ('code', models.CharField(choices=[('O2', 'O2'), ('AR', 'AR'), ('C2H2', 'C2H2'), ('N2', 'N2'), ('CO2', 'CO2')], max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_value', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='catalog.customer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'raw_value'), name='uniq_customer_alias_raw')],
            },
        ),
    ]
