# Generated by Django 5.2.17 on 2026-09-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeralias',
            name='normalized_value',
            field=models.CharField(blank=True, db_index=True, help_text='Trim+uppercase+collapse spasi dari raw_value - dipakai F4 untuk kandidat match exact-normalized (FR-03). Diisi oleh pemanggil, bukan otomatis di save().', max_length=255),
        ),
    ]
