# Generated by Django 5.2.17 on 2026-09-16 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('sent_at', models.DateField()),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('RETURNED', 'Returned'), ('EXCHANGED', 'Exchanged'), ('LOST', 'Lost'), ('REVERSED', 'Reversed')], default='', max_length=20)),
                ('date_unknown', models.BooleanField(default=False, help_text='True bila tanggal kembali/tutup siklus tidak diketahui pasti (mis. migrasi legacy).')),
                ('data_quality_flag', models.CharField(blank=True, default='', help_text='Mis. NEEDS_REVIEW bila jenis gas tidak dikenal saat dispatch. Terpisah dari status siklus.', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='catalog.customer')),
                ('cylinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='catalog.cylinder')),
                ('gas_type_at_dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.gastype')),
                ('replaced_by', models.OneToOneField(blank=True, help_text='Diisi saat siklus ini ditutup lewat pertukaran (EXCHANGED) - menunjuk siklus baru.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='operations.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(help_text="Nama command, mis. 'dispatch', 'return'.", max_length=32)),
                ('key', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('result_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.cycle')),
                ('result_cylinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cylinder')),
            ],
        ),
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('RETURNED', 'Returned'), ('EXCHANGED_OUT', 'Exchanged out'), ('EXCHANGED_IN', 'Exchanged in'), ('LOST', 'Lost'), ('MAINTENANCE_STARTED', 'Maintenance started'), ('MAINTENANCE_COMPLETED', 'Maintenance completed'), ('RETIRED', 'Retired'), ('REVERSED', 'Reversed')], max_length=30)),
                ('occurred_at', models.DateField(blank=True, null=True)),
                ('date_unknown', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('TELEGRAM', 'Telegram'), ('IMPORT', 'Import'), ('SYSTEM', 'System')], default='WEB', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='operations.cycle')),
                ('cylinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='catalog.cylinder')),
                ('reversed_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_of_set', to='operations.lifecycleevent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['customer', 'status'], name='operations__custome_5ed8e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('cylinder',), name='uniq_open_cycle_per_cylinder'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('scope', 'actor', 'key'), name='uniq_idempotency_scope_actor_key'),
        ),
        migrations.AddIndex(
            model_name='lifecycleevent',
            index=models.Index(fields=['cylinder', 'created_at'], name='operations__cylinde_e6c23d_idx'),
        ),
    ]
