# Generated by Django 5.2.17 on 2026-09-16 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_cycle_status_consistency_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='data_quality_flag',
            field=models.CharField(blank=True, default='', help_text='Mis. NEEDS_REVIEW bila gas tidak dikenal saat dispatch.', max_length=20),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='date_unknown',
            field=models.BooleanField(default=False, help_text='True bila tanggal kembali/tutup siklus tidak diketahui pasti.'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='replaced_by',
            field=models.OneToOneField(blank=True, help_text='Diisi saat siklus ditutup lewat pertukaran (EXCHANGED).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='operations.cycle'),
        ),
    ]
