# Generated by Django 5.2.17 on 2026-09-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_lifecycleevent_corrected'),
    ]

    operations = []
